function [dudt,model] = kernel_Derivative_bSpline5D(xi,yi,zi,ui,vi,nDatax,nDatay,nDataz,nDatau,nDatav,cMat,delta_f,delta_dfx,delta_dfy,delta_dfz,delta_dfu,delta_dfv,theta)

xc = floor(xi);
% sx= xi-xc;
yc = floor(yi);
% sy= yi-yc;
zc = floor(zi);
% sz= zi-zc;
uc = floor(ui);

vc = floor(vi);


xc = max(xc,1);
xc = min(xc,nDatax-1);

yc = max(yc,1);
yc = min(yc,nDatay-1);

zc = max(zc,1);
zc = min(zc,nDataz-1);

uc = max(uc,1);
uc = min(uc,nDatau-1);

vc = max(vc,1);
vc = min(vc,nDatav-1);

if vi == nDatav
    vc=nDatav;
end

if ui == nDatau
    uc=nDatau;
end

if xi == nDatax
    xc=nDatax;
end

if yi == nDatay
    yc=nDatay;
end

if zi == nDataz
    zc=nDataz;
end


kx = xc+1;
ky = yc+1;
kz = zc+1;
ku = uc+1;
kv = vc+1;
% dkx = kx+1;
% dky = ky+1;
% dkz = kz+1;

mx = 1;
my = 1;
mz = 1;
mu = 1;
mv = 1;
% dmx = 0;
% dmy = 0;
% dmz = 0;

f = single(0);
dfx = single(0);
dfy = single(0);
dfz = single(0);
dfu = single(0);
dfv = single(0);

nIndex = 0;
for s= 1:2
    for r = 1:2
        for q = 1:2
            for j = 1:2
                for i = 1:2

                    f = f+ ...
                        cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+1)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+2)+ ...
                        cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+3)+ ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+4)+ ...
                        cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+5)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+6) + ...
                        cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+7) + ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)* delta_f(32*nIndex+8)+...
                        cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+9)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+10)+ ...
                        cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+11)+ ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+12)+ ...
                        cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+13)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+14) + ...
                        cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+15) + ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)* delta_f(32*nIndex+16) + ...%additional dimension
                        cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+17)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+18)+ ...
                        cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+19)+ ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+20)+ ...
                        cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+21)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+22) + ...
                        cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+23) + ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)* delta_f(32*nIndex+24)+...
                        cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+25)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+26)+ ...
                        cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+27)+ ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+28)+ ...
                        cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+29)+ ...
                        cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+30) + ...
                        cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+31) + ...
                        cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)* delta_f(32*nIndex+32);


                    dfx = dfx+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my+1,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+1)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my+1,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+2)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my+1,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+3)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my+1,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+4)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my+1,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+5)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my+1,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+6) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my+1,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+7) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my+1,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfx(32*nIndex+8)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my+1,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+9)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my+1,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+10)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my+1,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+11)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my+1,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+12)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my+1,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+13)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my+1,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+14) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my+1,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+15) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my+1,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfx(32*nIndex+16)+ ...%additional dimension
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my+1,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+17)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my+1,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+18)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my+1,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+19)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my+1,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+20)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my+1,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+21)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my+1,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+22) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my+1,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+23) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my+1,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfx(32*nIndex+24)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my+1,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+25)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my+1,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+26)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my+1,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+27)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my+1,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+28)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my+1,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+29)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my+1,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+30) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my+1,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+31) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my+1,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfx(32*nIndex+32);
                        




                    dfy = dfy+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx+1,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+1)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx+1,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+2)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx+1,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+3)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx+1,kz-q+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+4)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx+1,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+5)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx+1,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+6) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx+1,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+7) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx+1,kz+q-1+mz,ku-r+mu,kv-s+mv))* delta_dfy(32*nIndex+8)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx+1,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+9)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx+1,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+10)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx+1,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+11)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx+1,kz-q+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+12)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx+1,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+13)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx+1,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+14) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx+1,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+15) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx+1,kz+q-1+mz,ku+r+mu-1,kv-s+mv))* delta_dfy(32*nIndex+16)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx+1,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+17)+ ...%additional dimension
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx+1,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+18)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx+1,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+19)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx+1,kz-q+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+20)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx+1,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+21)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx+1,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+22) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx+1,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+23) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx+1,kz+q-1+mz,ku-r+mu,kv+s+mv-1))* delta_dfy(32*nIndex+24)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx+1,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+25)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx+1,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+26)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx+1,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+27)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx+1,kz-q+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+28)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx+1,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+29)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx+1,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+30) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx+1,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+31) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx+1,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfy(32*nIndex+32);




                    dfz = dfz+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz-q+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+1)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+2)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+3)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+4)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+5)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+6) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+7) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz+1,ku-r+mu,kv-s+mv))* delta_dfz(32*nIndex+8)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz-q+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+9)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+10)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+11)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+12)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+13)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+14) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+15) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz+1,ku+r+mu-1,kv-s+mv))* delta_dfz(32*nIndex+16)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+17)+ ...%additional dimension
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+18)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+19)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+20)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+21)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+22) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+23) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz+1,ku-r+mu,kv+s+mv-1))* delta_dfz(32*nIndex+24)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+25)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+26)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+27)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+28)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+29)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+30) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+31) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz+1,ku+r+mu-1,kv+s+mv-1))* delta_dfz(32*nIndex+32);
                        



                    dfu = dfu+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+1)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+2)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+3)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+4)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+5)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+6) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+7) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu+1,kv-s+mv))* delta_dfu(32*nIndex+8)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+9)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+10)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+11)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+12)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+13)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+14) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu,kv-s+mv))* delta_dfu(32*nIndex+15) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+16)+ ...%additional dimension
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+17)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+18)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+19)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+20)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+21)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+22) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+23) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu+1,kv+s+mv-1))* delta_dfu(32*nIndex+24)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+25)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+26)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+27)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+28)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+29)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+30) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+31) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu,kv+s+mv-1))* delta_dfu(32*nIndex+32);

                    dfv = dfv+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+1)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+2)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+3)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+4)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+5)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+6) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+7) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv-s+mv+1))* delta_dfv(32*nIndex+8)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+9)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+10)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+11)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+12)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+13)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+14) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv-s+mv+1))* delta_dfv(32*nIndex+15) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1))* delta_dfv(32*nIndex+16)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+17)+ ...%additional dimension
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+18)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+19)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+20)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+21)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+22) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+23) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku-r+mu,kv+s+mv))* delta_dfv(32*nIndex+24)+...
                        (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+25)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+26)+ ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+27)+ ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+28)+ ...
                        (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+29)+ ...
                        (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+30) + ...
                        (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+31) + ...
                        (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,ku+r+mu-1,kv+s+mv))* delta_dfv(32*nIndex+32);





                    nIndex = nIndex+1;
                end
            end
        end
    end
end









dudt(1) = -1*theta(3)*dfy;
dudt(2) = -1*theta(3)*dfx;
% dudt(5) = theta(3)*dfz;
% dudt(6) = theta(3)*dfw;


dudt(5) = theta(3)*dfz;
dudt(6) = theta(3)*dfu;
dudt(7) = theta(3)*dfv;

dudt(3) = f;
dudt(4) = 1;
model = single(theta(4)+theta(3)*f);









