% function [dudt,model] =  kernel_Derivative_bSpline(zc,yc,xc,xsize,ysize,zsize,delta_f,delta_dxf,delta_dyf,delta_dzf,coeff,theta)

function [dudt,model] = kernel_Derivative_bSpline4D_v2(xi,yi,zi,wi,nDatax,nDatay,nDataz,nDataw,cMat,delta_f,delta_dfx,delta_dfy,delta_dfz,delta_dfw,theta)

xc = floor(xi);
% sx= xi-xc;
yc = floor(yi);
% sy= yi-yc;
zc = floor(zi);
% sz= zi-zc;
wc = floor(wi);

xc = max(xc,1);
xc = min(xc,nDatax-1);

yc = max(yc,1);
yc = min(yc,nDatay-1);

zc = max(zc,1);
zc = min(zc,nDataz-1);

wc = max(wc,1);
wc = min(wc,nDataw-1);

if wi == nDataw
    wc=nDataw;
end

if xi == nDatax
    xc=nDatax;
end

if yi == nDatay
    yc=nDatay;
end

if zi == nDataz
    zc=nDataz;
end
sz=[0,size(cMat,1),size(cMat,1)*size(cMat,2),size(cMat,1)*size(cMat,2)*size(cMat,3),size(cMat,1)*size(cMat,2)*size(cMat,3)*size(cMat,4)];
kx = xc+1;
ky = yc+1;
kz = zc+1;
kw = wc+1;

% dkx = kx+1;
% dky = ky+1;
% dkz = kz+1;

mx = 1;
my = 1;
mz = 1;
mw = 1;

% dmx = 0;
% dmy = 0;
% dmz = 0;

f = single(0);
dfx = single(0);
dfy = single(0);
dfz = single(0);
dfw = single(0);
nIndex = 0;
for r = 1:2
    for q = 1:2
        for j = 1:2
            for i = 1:2
                
                f = f+ ...
                    cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+1)+ ...
                    cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+2)+ ...
                    cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+3)+ ...
                    cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+4)+ ...
                    cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+5)+ ...
                    cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+6) + ...
                    cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+7) + ...
                    cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))* delta_f(16*nIndex+8)+...
                    cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+9)+ ...
                    cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+10)+ ...
                    cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+11)+ ...
                    cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+12)+ ...
                    cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+13)+ ...
                    cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+14) + ...
                    cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+15) + ...
                    cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))* delta_f(16*nIndex+16);
                
                
                
                dfx = dfx+ ...
                    (cMat(ky-i+my+1+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+1)+ ...
                    (cMat(ky+i-1+my+1+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+2)+ ...
                    (cMat(ky-i+my+1+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+3)+ ...
                    (cMat(ky+i-1+my+1+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+4)+ ...
                    (cMat(ky-i+my+1+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+5)+ ...
                    (cMat(ky+i-1+my+1+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+6) + ...
                    (cMat(ky-i+my+1+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+7) + ...
                    (cMat(ky+i-1+my+1+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4))-cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw-r+mw)*sz(4)))* delta_dfx(16*nIndex+8)+...
                    (cMat(ky-i+my+1+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+9)+ ...
                    (cMat(ky+i-1+my+1+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+10)+ ...
                    (cMat(ky-i+my+1+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+11)+ ...
                    (cMat(ky+i-1+my+1+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz-q+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+12)+ ...
                    (cMat(ky-i+my+1+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky-i+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+13)+ ...
                    (cMat(ky+i-1+my+1+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky+i-1+my+(kx-j+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+14) + ...
                    (cMat(ky-i+my+1+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky-i+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+15) + ...
                    (cMat(ky+i-1+my+1+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4))-cMat(ky+i-1+my+(kx+j-1+mx)*sz(2)+(kz+q-1+mz)*sz(3)+(kw+r+mw-1)*sz(4)))* delta_dfx(16*nIndex+16);
                
                
                
                
                dfy = dfy+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx+1,kz-q+mz,kw-r+mw))* delta_dfy(16*nIndex+1)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx+1,kz-q+mz,kw-r+mw))* delta_dfy(16*nIndex+2)+ ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx+1,kz-q+mz,kw-r+mw))* delta_dfy(16*nIndex+3)+ ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx+1,kz-q+mz,kw-r+mw))* delta_dfy(16*nIndex+4)+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx+1,kz+q-1+mz,kw-r+mw))* delta_dfy(16*nIndex+5)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx+1,kz+q-1+mz,kw-r+mw))* delta_dfy(16*nIndex+6) + ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx+1,kz+q-1+mz,kw-r+mw))* delta_dfy(16*nIndex+7) + ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx+1,kz+q-1+mz,kw-r+mw))* delta_dfy(16*nIndex+8)+...
                    (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx+1,kz-q+mz,kw+r+mw-1))* delta_dfy(16*nIndex+9)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx+1,kz-q+mz,kw+r+mw-1))* delta_dfy(16*nIndex+10)+ ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx+1,kz-q+mz,kw+r+mw-1))* delta_dfy(16*nIndex+11)+ ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx+1,kz-q+mz,kw+r+mw-1))* delta_dfy(16*nIndex+12)+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx+1,kz+q-1+mz,kw+r+mw-1))* delta_dfy(16*nIndex+13)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx+1,kz+q-1+mz,kw+r+mw-1))* delta_dfy(16*nIndex+14) + ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx+1,kz+q-1+mz,kw+r+mw-1))* delta_dfy(16*nIndex+15) + ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx+1,kz+q-1+mz,kw+r+mw-1))* delta_dfy(16*nIndex+16);
                
                
                
                
                dfz = dfz+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx,kz-q+mz+1,kw-r+mw))* delta_dfz(16*nIndex+1)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz+1,kw-r+mw))* delta_dfz(16*nIndex+2)+ ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz+1,kw-r+mw))* delta_dfz(16*nIndex+3)+ ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz+1,kw-r+mw))* delta_dfz(16*nIndex+4)+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz+1,kw-r+mw))* delta_dfz(16*nIndex+5)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz+1,kw-r+mw))* delta_dfz(16*nIndex+6) + ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz+1,kw-r+mw))* delta_dfz(16*nIndex+7) + ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz+1,kw-r+mw))* delta_dfz(16*nIndex+8)+...
                    (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+9)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+10)+ ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+11)+ ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+12)+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+13)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+14) + ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+15) + ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz+1,kw+r+mw-1))* delta_dfz(16*nIndex+16);
                
                
                
                dfw = dfw+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+1)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+2)+ ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+3)+ ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+4)+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+5)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+6) + ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+7) + ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+8)+...
                    (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz,kw+r+mw))* delta_dfw(16*nIndex+9)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw+r+mw))* delta_dfw(16*nIndex+10)+ ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw+r+mw))* delta_dfw(16*nIndex+11)+ ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw+r+mw))* delta_dfw(16*nIndex+12)+ ...
                    (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw+r+mw))* delta_dfw(16*nIndex+13)+ ...
                    (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw+r+mw))* delta_dfw(16*nIndex+14) + ...
                    (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw))* delta_dfw(16*nIndex+15) + ...
                    (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw))* delta_dfw(16*nIndex+16);
                
                
                
%                 
%                 
%                 dfw = dfw+ ...
%                     (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+1)+ ...
%                     (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+2)+ ...
%                     (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+3)+ ...
%                     (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw-r+mw+1))* delta_dfw(16*nIndex+4)+ ...
%                     (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+5)+ ...
%                     (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+6) + ...
%                     (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+7) + ...
%                     (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw-r+mw+1))* delta_dfw(16*nIndex+8)+...
%                     (-1*cMat(ky-i+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx,kz-q+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+9)+ ...
%                     (-1*cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx,kz-q+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+10)+ ...
%                     (-1*cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+11)+ ...
%                     (-1*cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx,kz-q+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+12)+ ...
%                     (-1*cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+13)+ ...
%                     (-1*cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx-j+mx,kz+q-1+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+14) + ...
%                     (-1*cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky-i+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+15) + ...
%                     (-1*cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1)+cMat(ky+i-1+my,kx+j-1+mx,kz+q-1+mz,kw+r+mw-1+1))* delta_dfw(16*nIndex+16);
%                 
%                 
                
                
                nIndex = nIndex+1;
            end
        end
    end
end
















% [temp,dfx,dfy,dfz] = fAt3D_bs_v6(xc+jj+off,yc+ii+off,zc,dataSize(1),dataSize(2),dataSize(3),b3.coeffs,delta_f,delta_dfx,delta_dfy,delta_dfz);




dudt(1) = -1*theta(3)*dfy;
dudt(2) = -1*theta(3)*dfx;
% dudt(5) = theta(3)*dfz;
% dudt(6) = theta(3)*dfw;


dudt(5) = theta(3)*dfz;
dudt(6) = theta(3)*dfw;

dudt(3) = f;
dudt(4) = 1;
model = single(theta(4)+theta(3)*f);








% dudt = zeros(5,1);
% xc = max(xc,0);
% xc = min(xc,xsize-1);
% 
% yc = max(yc,0);
% yc = min(yc,ysize-1);
% 
% zc = max(zc,0);
% zc = min(zc,zsize-1);
% 
% temp = coeff(xc+1,yc+1,zc+1,:);
% dudt(1)=-1*theta(3)*sum(delta_dxf.*(temp(:)));
% dudt(2)=-1*theta(3)*sum(delta_dyf.*(temp(:)));
% dudt(5)=theta(2)*sum(delta_dzf.*(temp(:)));
% dudt(3)=sum(delta_f.*(temp(:)));
% dudt(4)=1;
% model = theta(4)+theta(3)*dudt(3);

